### ISSUE TITLE
Working with custom datasets and SG detection formats

### ISSUE THREAD

**Issue by wematan** [Deci-AI/super-gradients#1012]
Hi,

I'm trying to train a yolox model using my own custom dataset.
The reason im using a custom dataset is becuase of the caching machenizem used in SG dataset objects which results in super long dataset loading time and Memory Error for (very) large datasets.

So far i've been successfull in implementing a somewhat uncached version ofo SG's DetectionDataset.
I'm also working with clearml datasets so i added the option of fetching a dataset from clearml server and loading the dataset metadata.

I've also used the plot function to plot my dataset samples which works well when not using any transforms.
But my issue is with the transformations (copied the transform pipeline from the yolox yaml config) and specifically with Mosaic (since it is also the first one and probably screws up my labels)

The transformations do work on the image part, i'm getting nice augmented images, but the labels don't make sense.
i tried working with different detection formats (LABEL_CXCYWH, LABEL_XYWH, LABEL_XYXY) but no luck.
when investigating the mosaic code it is vaguely documented but just above the operation that is done on the labels there's a comment 
`# Normalized xywh to pixel xyxy format` - line 506.
which is uclear to me since in your coco detection dataset the XYXY_LABEL format is used, but it succefully transforms the label as well when using that dataset.

my question is what is the expected input format to the transforms?

**Comment by Louis-Dupont** [comment]
Hi @wematan ,

Caching the annotations led to a Memory Error ?  We have a ticket to make the cache optional, but it was just never prioritized enough because, until now, it never led to this situation of crashing the code.

The transforms expect a sample `{"image": <np.ndarray>, "target": <np.ndarray>}`, except for mosaic which expects another field `{"additional_samples": List[{"image": <np.ndarray>, "target": <np.ndarray>}]}.` made of 3 samples.
Mosaic will combine the main sample with the additional 3 together into a single image/label.
FYI, we add the samples in our dataset here: https://github.com/Deci-AI/super-gradients/blob/b4608f618a60de1504211f75e14f9fc7ade2874a/src/super_gradients/training/datasets/detection_datasets/detection_dataset.py#L378-L393


#### Other information about our transforms
- All of our transforms expect the target to be (x, y, x, y, label) - including **Mosaic**
- The transforms are applied on a single sample, not batch


#### About YoloX
It expects
- image to be of shape [C, H, W]
- target to be padded using `DetectionTargetsFormatTransform` (required), which is [max_targets, 5] with max_targets a parameter to the Transorm and 5 for (label, cx, cy, w, h). 


If this doesn't answer your question or if you have another problem, you can share the code you implemented, it could help me be more precise in my answer :)

**Comment by wematan** [comment]
@Louis-Dupont Thanks a lot for your quick and elaborate response.

I've finally got it to work now.
Regardig caching, yes it is an issue since most end2end training frameworks focus on implementing as many models as they can but only benchmark those on a specific type of datasets (which unfortunately are of small capacity), it became harder to train (very) large datasets (10M> objects).

BR,
Matan.
