### ISSUE TITLE
YOLO-NAS + BOXMOT (YOLO-NAS multi-object tracking)

### ISSUE THREAD

**Issue by mikel-brostrom** [Deci-AI/super-gradients#1066]
### 🚀 Feature Request

I have [an example in my repository](https://github.com/mikel-brostrom/yolo_tracking/blob/737b6ae62b206f718781d3de2398859010e6dcd9/examples/yolo_nas_track.py) on how to integrate SOTA tracking methods together with Yolo-NAS.

 I am using the Yolov8 backend functionality to achieve this. This is only because I am more familiar with it. I am certain it would be equally easy with the `super-gradients` backend :smile: 

My pip package contain SOTA tracking methods: both motion only and motion + ReID. Pairing up `boxmot` together with `yolo-nas` is seamless and leads to very good results out of the box.

### Proposed Solution (Optional)

Adapt [this](https://github.com/mikel-brostrom/yolov8_tracking/blob/master/examples/yolo_nas_track.py) to super-gradients backend

**Comment by mikel-brostrom** [comment]
I fixed some bugs. It is stable now.

**Comment by ofrimasad** [comment]
Wow!! This is great!
Thank you @mikel-brostrom for this fantastic contribution.
We can't include the code in our repo, since unfortunately, it is under AGPL 3.0 license (our repo is Apache 2.0). 
But we will definitely add a Colab notebook on how to use BOXMOT + YOLO-NAS and points to your repo of course. 
Thanks :)

**Comment by mikel-brostrom** [comment]
Nice! I will keep this open in case you need support integrating this :smile:
