### ISSUE TITLE
YOLO-NAS with NPU. Possible?

### ISSUE THREAD

**Issue by Tsardoz** [Deci-AI/super-gradients#1095]
### 💡 Your Question

There is much written about using INT8 quantization (QAT and PTQ) with YOLO-NAS.
However, I can find nothing about using it with NPUs.
It seems to be designed for CPU use and to work with NPUs the model structure must be changed.
Is that right?
If so, are there plans for NPU versions?

**Comment by mikel-brostrom** [comment]
Deci-AI cannot provide NPU model versions for you. This is because you need to compile a program for the specific chip you run your models on. It makes no sense to provide compiled model version for all the chips (and their different versions) in existence. Each of them have an associated toolchain that is completely different to another chips' toolchain. Which makes it close to impossible to build a unified NPU exporter that matches you specific hardware setup.
