### ISSUE TITLE
.hydra folder not created , but why?

### ISSUE THREAD

**Issue by prankshtain** [Deci-AI/super-gradients#1123]
### 💡 Your Question

I don't know why but when I want to start training from the last checkpoint based on what is in here: https://github.com/Deci-AI/super-gradients/blob/b4eec926261e9e8f3032d8fb51977af33b85ec3c/src/super_gradients/common/environment/omegaconf_utils.py#L74

I get the error: File Error: does not include .hydra artifacts to resume the experiment.

two questions :
1. why not this thing not created when I started training?
2. is there any way that I can resume training without this folder included in the solution?
NOTE: I need the exact Python code to resume it not the CLI command 

thanks a lot for developing the fastest Yolo model in history :)

**Comment by shaydeci** [comment]
Hey @prankshtain , the hydra output directory is created when [training with configs](https://docs.deci.ai/super-gradients/documentation/source/configuration_files.html) (otherwise it does not make much sense, since instantiated objects instead of configs can be passed too). 

If you did train_with_configs, the .hydra directory should be under your <CHECKPOINTS_DIR>/<EXPERIMENT_NAME>.

Can you elaborate if what is the situation?

**Comment by harpreetsahota204** [comment]
Hey @prankshtain 

Thanks for opening an issue for SG. I'm gathering some feedback on SuperGradients and YOLO-NAS.

Would you be down for a quick call to chat about your experience?

If a call doesn't work for you, no worries. I've got a short survey you could fill out: https://bit.ly/sgyn-feedback.

I know you’re super busy, but your input will help us shape the direction of SuperGradients and make it as useful as possible for you.

I appreciate your time and feedback. Let me know what works for you.

Cheers,

Harpreet

**Comment by BloodAxe** [comment]
Closing as stale
