### ISSUE TITLE
Why is precision so low for yolo-nas model ?

### ISSUE THREAD

**Issue by HissaanAli** [Deci-AI/super-gradients#1191]
### 💡 Your Question

I trained a `yolo-nas` model for an object detection dataset and I noticed something weird. The recall and `mAP` value of the model were at **98%** and **95%**  respectively however the precision was barely **20%**. 

This comes off as a surprise to me that how is the mAP and recall high, but the precision so low. Why is that ? Can somebody elaborate ?

The same model when trained with **yolov5** gave precision, recall and mAP value of **94%**.

**Comment by ofrimasad** [comment]
Hi @HissaanAli .
It sounds like you need to tune the confidence level of the NMS. 
In the post prediction callback, pass `conf=0.9`, for example. And see if the precision-recall tradeoff looks better

**Comment by ahmad2246** [comment]
> 

@ofrimasad can you kindly elaborate more on how to change it? because I'm facing the same issue here of low precision while having high recall

I know how tochange the conf value when predicting an image like that:

model.predict(image_path, conf=0.5).show()

but I don't know from where should i change the conf value for the training and evaluation processes
