### ISSUE TITLE
Does model.predict() only work on image of size 640x640?

### ISSUE THREAD

**Issue by Dev-Devesu** [Deci-AI/super-gradients#1402]
### 💡 Your Question

can i use the model to predict on different sizes of image like we do in yolov5?
can i use something like model.predict(image, size=1280) ?
is something like this supported if not then what should di do if my video/image is in different size?

**Comment by BloodAxe** [comment]
You can use arbitrary sized inputs in `predict`. The input image will be send through the same preprocessing pipeline as was used during training in validation loader (Resizing to 640 max size + padding). Currently there is no `easy` way to override inference size (Like you mentioned with `size=1280`). 
You can however override dataset processing params before calling predict to specify the desired inference size.

**Comment by bit-scientist** [comment]
@Dev-Devesu, in addition to what @BloodAxe mentioned, I would generally only try the image sizes similar to what my model was trained with. For example, if your model was trained with 640, then it's OK to use sizes 800, 736, 640, 576, 512. Because as stated above the input will be pre-processed. These sizes won't degrade the image quality that much. However, if you try twice or thrice the size of the training size, then there will be a great deal of quality loss.

**Comment by Dev-Devesu** [comment]
i am using 1920*1080 size video and i wanted to iterate through the frames. but since the model is getting trained on 640*640 images then will i be getting decent results? I am custom training the dataset. for my project i am using custom annotations but the bounding boxes are not in right places. why could this be? Also I am passing the detection of nas to bytetrack but the ID and annotations are stuck in 1 frame and not getting dynamically updated in each frame

**Comment by Dev-Devesu** [comment]
![image](https://github.com/Deci-AI/super-gradients/assets/120472113/8328f53f-890a-4a9d-bd21-b18ebd67d1e8)

**Comment by BloodAxe** [comment]
We support mode to disable image resizing: `model.predict(image, skip_image_resizing=True)`
