### ISSUE TITLE
Graphics card usage is unevenly distributed

### ISSUE THREAD

**Issue by xxxsmlie** [Deci-AI/super-gradients#1594]
### 💡 Your Question

When I use ddp mode and use 4 3090 images to train my data set, the graphics card memory usage is extremely uneven. Why is this? Is there any way to solve it?

**Comment by BloodAxe** [comment]
Could be anything from slow CPU that is not able to prepare data fast enough for your cards or to nature of your data (Maybe it takes longer to prepare some of your images).

Since you did not provide any additional information on your HW setup, task that you are training, htop/nvtop outputs it is impossible to assist you with your issue.
