### ISSUE TITLE
Sagemaker Inference for Video

### ISSUE THREAD

**Issue by rvryan67** [Deci-AI/super-gradients#1676]
### 💡 Your Question

I'm having a issue reading prediction results when I run a predict() on a video file.

example:

```
model = super_gradients.training.models.get("yolo_nas_m", num_classes=1, checkpoint_path=r"yolo_nas_m/ckpt_best.pth").cuda()

predictions = model.predict(url, conf=0.1, iou=0.1, fuse_model=False)
print(predictions)

#returns
#VideoDetectionPrediction(_images_prediction_gen=<generator object Pipeline._generate_prediction_result at 0x7f77f7e9ce40>, fps=25.0, n_frames=299)



```

If I try to iterate the predictions I get a "object is not iterable" error

```
predictionslist = list(predictions)
#TypeError: 'VideoDetectionPrediction' object is not iterable

```

**Comment by BloodAxe** [comment]
`save` method is a member of `predictions` object, not of the generator.

Please keep in mind that calling `list(predictions._images_prediction_gen)` and then `predictions.save` would lead to double inference.

Now we don't cache the predictions due to some implementation complexities so if you are ok with increased processing time this can be a way to go. If not then I suggest you to store box coordinates manually (excluding the image frame) and then generate visualization video by hand.

The whole idea of this design is to ensure that you are not accumulating all image frames in RAM and won't get OOM error if the video is too long/large.
