### ISSUE TITLE
Problem when importing models out of the terminal

### ISSUE THREAD

**Issue by sergiovillanueva** [Deci-AI/super-gradients#1733]
### 🐛 Describe the bug

I have a conda environment and the latest versions of the libraries.
When I run my script in vscode or in the terminal it works perfectly.

But when I want to run my script, with the same conda environment in another execution environment like Python 4 Delphi, right on the line from super_gradients.training import models it gives me an error: AttributeError: 'NoneType' object has no attribute 'write' '

I have tried to follow the execution but I can't figure out why it gives me this error.

I normally use this Python 4 Delphi architecture with other environments and other libraries and it works without problems, because everything runs within the conda environment. but with this library it doesn't work for me.
Any idea why?

### Versions

j

**Comment by BloodAxe** [comment]
I think `Python 4 Delphi` does some magic with overriding stdin/stdouts which conflicts with some magic SG is also performing under the hood to log console outputs to log files. Unfortunately I don't think we are able to address this issue now. Probablly it relates to this [issue](https://github.com/Deci-AI/super-gradients/issues/1497) but the fix is not on the roadmap yet.
