### ISSUE TITLE
Bug on version 3.6 "ValueError: unknown file extension: " on prediction.save(), version 3.5 works ok.

### ISSUE THREAD

**Issue by Marco-2402** [Deci-AI/super-gradients#1836]
### 🐛 Describe the bug

This just happens in 3.6, same code in 3.5 works fine.

Easy: Do a simple prediction on any custom trainded model like this:

```Python
from super_gradients.training import models

device = torch.device("cuda:0") if torch.cuda.is_available() else torch.device("cpu")
model = models.get(
    model_name='yolo_nas_s',
    checkpoint_path='models/MyCustomTrainedModel.pth',
    num_classes=len(CLASSES),
    pretrained_weights="coco"
).to(device)
image_path = 'test/T_01_1920.jpg'
prediction = model.predict(image_path, iou=0.05, conf=0.3, skip_image_resizing=False)
prediction.save(output_path, box_thickness=2, show_confidence=True)
```

And Gets:

```BASH
Traceback (most recent call last):
  File "/opt/conda/envs/yon/lib/python3.9/site-packages/PIL/Image.py", line 2416, in save
    format = EXTENSION[ext]
KeyError: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ddata/4_predict.py", line 147, in <module>
    process_image(image, model, crops_dir, output_path)
  File "/ddata/4_predict.py", line 89, in process_image
    prediction.save(output_path, box_thickness=2, show_confidence=True)
  File "/opt/conda/envs/yon/lib/python3.9/site-packages/super_gradients/training/utils/predict/prediction_results.py", line 298, in save
    save_image(image=image, path=output_path)
  File "/opt/conda/envs/yon/lib/python3.9/site-packages/super_gradients/training/utils/media/image.py", line 149, in save_image
    Image.fromarray(image).save(path)
  File "/opt/conda/envs/yon/lib/python3.9/site-packages/PIL/Image.py", line 2419, in save
    raise ValueError(msg) from e
ValueError: unknown file extension:
```

### Versions

PyTorch version: 2.2.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.9.18 (main, Sep 11 2023, 13:41:44)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1050 Ti
Nvidia driver version: 546.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      46 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             20
On-line CPU(s) list:                0-19
Vendor ID:                          GenuineIntel
Model name:                         12th Gen Intel(R) Core(TM) i7-12700K
CPU family:                         6
Model:                              151
Thread(s) per core:                 2
Core(s) per socket:                 10
Socket(s):                          1
Stepping:                           2
BogoMIPS:                           7219.19
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq vmx ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves avx_vnni umip waitpkg gfni vaes vpclmulqdq rdpid movdiri movdir64b fsrm serialize flush_l1d arch_capabilities
Virtualization:                     VT-x
Hypervisor vendor:                  Microsoft
Virtualization type:                full
L1d cache:                          480 KiB (10 instances)
L1i cache:                          320 KiB (10 instances)
L2 cache:                           12.5 MiB (10 instances)
L3 cache:                           25 MiB (1 instance)
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Mitigation; Enhanced IBRS
Vulnerability Spec rstack overflow: Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] onnx==1.13.0
[pip3] onnx-simplifier==0.4.35
[pip3] onnxruntime==1.13.1
[pip3] onnxsim==0.4.35
[pip3] torch==2.2.0
[pip3] torchaudio==2.2.0+cu121
[pip3] torchmetrics==0.8.0
[pip3] torchvision==0.17.0
[pip3] triton==2.2.0
[conda] numpy                     1.23.0                   pypi_0    pypi
[conda] torch                     2.2.0                    pypi_0    pypi
[conda] torchaudio                2.2.0+cu121              pypi_0    pypi
[conda] torchmetrics              0.8.0                    pypi_0    pypi
[conda] torchvision               0.17.0                   pypi_0    pypi
[conda] triton                    2.2.0                    pypi_0    pypi

**Comment by BloodAxe** [comment]
In 3.6 the behavior of .save() method for single image has been changed. 
Since 3.6 the `output_path` of `save` method when single image is used is **a filename of the image to save, not the output directory**.

**Comment by BloodAxe** [comment]
So it should be like that:

```
image_path = 'test/T_01_1920.jpg'
prediction = model.predict(image_path, iou=0.05, conf=0.3, skip_image_resizing=False)
prediction.save(os.path.join(output_path, "T_01_1920.jpg"), box_thickness=2, show_confidence=True)
```

**Comment by rabion1234** [comment]
my model.predict() is showing error of Unidentified image error in google colab. this is full error: 
UnidentifiedImageError Traceback (most recent call last) in <cell line: 1>() ----> 1 best_model.predict("img2.jpg")

8 frames /usr/local/lib/python3.10/dist-packages/super_gradients/training/models/detection_models/customizable_detector.py in predict(self, images, iou, conf, batch_size, fuse_model, skip_image_resizing, nms_top_k, max_predictions, multi_label_per_box, class_agnostic_nms, fp16) 306 fp16=fp16, 307 ) --> 308 return pipeline(images, batch_size=batch_size) # type: ignore 309 310 def predict_webcam(

/usr/local/lib/python3.10/dist-packages/super_gradients/training/pipelines/pipelines.py in call(self, inputs, batch_size) 118 return self.predict_video(inputs, batch_size) 119 elif check_image_typing(inputs): --> 120 return self.predict_images(inputs, batch_size) 121 else: 122 raise ValueError(f"Input {inputs} not supported for prediction.")

/usr/local/lib/python3.10/dist-packages/super_gradients/training/pipelines/pipelines.py in predict_images(self, images, batch_size) 131 from super_gradients.training.utils.media.image import load_images 132 --> 133 images = load_images(images) 134 135 result_generator = self._generate_prediction_result(images=images, batch_size=batch_size)

/usr/local/lib/python3.10/dist-packages/super_gradients/training/utils/media/image.py in load_images(images) 32 :return: List of images as numpy arrays. If loaded from string, the image will be returned as RGB. 33 """ ---> 34 return [image for image in generate_image_loader(images=images)] 35 36

/usr/local/lib/python3.10/dist-packages/super_gradients/training/utils/media/image.py in (.0) 32 :return: List of images as numpy arrays. If loaded from string, the image will be returned as RGB. 33 """ ---> 34 return [image for image in generate_image_loader(images=images)] 35 36

/usr/local/lib/python3.10/dist-packages/super_gradients/training/utils/media/image.py in generate_image_loader(images) 66 yield load_image(image=image) 67 else: ---> 68 yield load_image(image=images) 69 70

/usr/local/lib/python3.10/dist-packages/super_gradients/training/utils/media/image.py in load_image(image, input_image_channels) 120 return load_np_image_from_pil(image) 121 elif isinstance(image, str): --> 122 image = load_pil_image_from_str(image_str=image) 123 return load_np_image_from_pil(image) 124 else:

/usr/local/lib/python3.10/dist-packages/super_gradients/training/utils/media/image.py in load_pil_image_from_str(image_str) 139 return PIL.Image.open(io.BytesIO(response.content)) 140 else: --> 141 return PIL.Image.open(image_str) 142 143

/usr/local/lib/python3.10/dist-packages/PIL/Image.py in open(fp, mode, formats) 3281 continue 3282 except BaseException: -> 3283 if exclusive_fp: 3284 fp.close() 3285 raise

UnidentifiedImageError: cannot identify image file 'img2.jpg' 

i tried to traceback and my image path was correct and image is not corrupted because when i tried with  train_data.dataset._load_image("img2.jpg") it is opening. 

for more i am attaching my code in google colab: https://colab.research.google.com/drive/17DGZzUHsaClbjiJPlfDadmx4x9sX-aYC?usp=sharing

previously it was working fine but now suddenly this error comes. I checked image path is correct.  also image name is correct.
I tried to open image using PIL but still error was same and tried using other image but error is same and unsolved.
