### ISSUE TITLE
How to accelerate regseg on tensorRT

### ISSUE THREAD

**Issue by odyssey0529** [Deci-AI/super-gradients#217]
I tried to use tensorrt with original regseg repository.
However onnx had trouble with torch.split and also torch2trt unable to use with specific tensorrt version.
Please let me know how did you use tensorrt with regseg model when measure the latency.

**Comment by oferbaratz** [comment]
Hi,
So we are using the Deci platform in order to compile and optimize the runtime performance. You choose there the target HW that you will use, and if it's Nvidia's HW it will compile it using trt.
You can try using the platform and load there your onnx model - https://console.deci.ai/
we can also assist you with deployment issues via Deci community slack channel  - https://join.slack.com/t/decicommunity/shared_invite/zt-1b0pfclld-SEyaCUQxafr~7LWuPM9H~Q

**Comment by odyssey0529** [comment]
Since RegSeg's original repository saved model as zip file, how did you convert it to onnx?
