### ISSUE TITLE
Label visualization for datasets

### ISSUE THREAD

**Issue by jacobmarks** [Deci-AI/super-gradients#935]
### Is your feature request related to a problem? Please describe.
Currently, when a prediction object is generated for an image, the only ways to visualized those predictions are via the `show()` and `save()` methods, both of which "draw" the labels onto the image. This has the following limitations:

- user cannot inspect properties of the labels directly
- user cannot compare those predictions easily to predictions from other models
- the `save()` creates a duplicate image, which can be storage-inefficient, especially when done for a lot of images
- it is not possible to natively visualize the predictions for a set of images (a dataset)

### Describe the solution you'd like
Use open-source computer vision library [FiftyOne](https://github.com/voxel51/fiftyone) for visualization and management of Deci AI model predictions. This can be either a stand-in replacement for the current `show()` method, (which, by the way, would allow for extending `show()` to lists of results objects), or as an option you can pass into `show()`.

For a detailed illustration, check out this Medium blog post on [State-of-the-Art Object Detection with YOLO-NAS & FiftyOne](https://medium.com/voxel51/state-of-the-art-object-detection-with-yolo-nas-fiftyone-f1530826b28e)

**Comment by BloodAxe** [comment]
Hi there. We do provide visualisation of predictions. I agree that maybe it's not that rich as FiftyOne offers. However, for it's intended use case (Showing results in notebooks) it does the job.

As you showed in post on Medium, one need to write some adapter code to convert predictions to the format required by FiftyOne. And I don't see anything wrong with this approach since or how it could be improved on our side. 

If you have a specific proposal for changing the API of prediction pipeline in Super Gradients - please share them here, since it's not quite clear how you see this change.
