### ISSUE TITLE
[BUG]I can not install super-gradients on Jetson AGX Orin

### ISSUE THREAD

**Issue by storm12t48** [Deci-AI/super-gradients#984]
I can't install super-gradients on Jetson because i cant  Generating metadata for package onnx-simplifier 

Rapport erreur package : 

```
(Detection) root@ubuntu:/home/AthisDetection2/Detection# pip install -qU super-gradients imutils
WARNING: The directory '/root/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
  WARNING: Generating metadata for package onnx-simplifier produced metadata for project name onnxsim. Fix your #egg=onnx-simplifier fragments.
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 357, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 370, in _resolve_one
    assert req_to_install.is_direct
AssertionError
```
but i can build and install alone , I admit that I have a lot of difficulty installing, I had to go through a script [here](https://github.com/daquexian/onnx-simplifier/issues/214#issuecomment-1315465297) and I did an --upgrade of the install to have the version requested by super-gradient:

```
Successfully built onnxsim onnxsim
Installing collected packages: onnxsim
  Attempting uninstall: onnxsim
    Found existing installation: onnxsim 0.4.9
    Uninstalling onnxsim-0.4.9:
      Successfully uninstalled onnxsim-0.4.9
Successfully installed onnxsim-0.4.28

```

**Comment by BloodAxe** [comment]
Why do you think this issue is related to super-gradients? It looks like the problem with a 3rd-party package specific to Orin platform. I'm not sure there is any action required from our side.
What you can do, however is to install Super Gradients without dependencies:
`pip install --no-deps super-gradients`

This would install only super-gradients package without any dependencies, so you will have to go and manually install them from [requirements.txt](https://github.com/Deci-AI/super-gradients/blob/master/requirements.txt).
